feat: PB-107312 Manage multi-clientIds for oauth2 while keeping usage…
OneSpan/esl.sdk.java pull request #151
Opened 2024-07-11 18:46 UTC by ckeyrouz

- Deprecated the EslClient constructor that accepts OAuthTokenConfig
- Added EslClientProvider to replace the constructor above.
- Made the EslClientProvider a singleton with a concurrentHashMap to store all created EslClients
- Added a new getter for oauthTokenConfig in EslClient
- EslClientProvider will only create a new EslClient if it's never been created or if the clientSecret was modified.
- Unit testes the above scenarios

2024-07-11 20:32 UTC, gadheam1-oss requested changes

2024-07-11 20:32 UTC, gadheam1-oss commented on sdk/src/main/java/com/silanis/esl/sdk/provider/EslClientConfig.java
> +
Lets add a example implementing usage of EslClientProvider

2024-07-12 18:01 UTC, gadheam1-oss approved these changes

2024-07-12 20:19 UTC, gadheam1-oss approved these changes

2024-07-12 20:23 UTC, gadheam1-oss approved these changes

2024-07-12 20:39 UTC, gadheam1-oss approved these changes
Looks good

2024-07-12 20:39 UTC, marion35700 approved these changes

2024-07-12 20:56 UTC, houjianyu approved these changes

2024-07-12 20:56 UTC, merged